#!/bin/sh

        # cvsaddko : script for adding a tar or binary file

        cvs add -ko -m "Initial version." $1
        cvs commit -m "Initial version." $1
        cvs admin -ko $1
        rm -f $1
        cvs update $1
